### PR TITLE
Fix standard formatting

### PR DESCRIPTION
**Pull request by LinusU**
This is currently making our builds fail ☺️ 

https://travis-ci.org/standard/standard/jobs/415533047

### CODE REVIEW

**Comment by brodybits** [comment]
I already raised #62 to automatically check this, would be happy to rebase it if someone wants to take a look.

**Comment by eddiemoore** [comment]
@LinusU @brodybits We can use the update from @62. I'll close this one in favour of that one. Just need to fix the merge conflicts.

**Comment by eddiemoore** [comment]
fixes published at 3.0.5

**Comment by LinusU** [comment]
👍

**Pull request closed without merging**
